### ISSUE TITLE
Downloads not working 

### ISSUE THREAD

**Issue by Harun-Kahramanoglu** [Fantasy-Boss/9anime-Downloader#2]
So after scanning al the episodes and starting the download the download bar stops at 86% every time and then a lot of sbembed tabs open with a download button and when you click on it it says PLEASE CLICK DOWNLOAD TO VERIFY THAT YOU'RE NOT ROBOT!0
I checked by shutting the downloader and trying it manual and all episodes word and can be downloaded.

**Comment by Fantasy-Boss** [comment]
Thank you for your feedback.  the sbembed site seems to be down right now. so i cant check the problem. you will have to wait a bit more. I just wanted to let you know that i have received your report and any additional information would be helpful. please answer this questions to better identify the issue :-

1. When did the issue start happening ?
2. Did the script worked before on your device ?
3. Did the issue occur with multiple anime or just one particular anime ?
(Optional) - A screenshot of the issue would be helpful.

**Comment by Fantasy-Boss** [comment]
Sorry too say this, but they disabled bulk downloads. So this scraping won't work anymore. Nothing I can do about it. Goodbye to "9anime-Downloader".

![Annotation 2023-03-04 090641](https://user-images.githubusercontent.com/58109796/222913967-054847c9-2ea3-4423-8c81-a4dbd27b7628.png)
